
# https://github.com/mdobydullah/laravel-docker-apache-mariadb/blob/main/.docker/Dockerfile

# FROM php:7.4.29-apache
FROM php:7.4.29-apache-buster

USER root

RUN apt update && apt install -y \
        nodejs \
        npm \
        libpng-dev \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        libonig-dev \
        zip \
        curl \
        unzip mc 


RUN mkdir -p /var/www/html; chown -R 1000:www-data /var/www/html  &&  chmod -R 777 /var/www/html
WORKDIR /var/www/html

RUN pwd; ls -la; docker-php-ext-install -j$(nproc) gd 
RUN docker-php-ext-configure gd 
RUN docker-php-ext-install pdo_mysql 
RUN docker-php-ext-install mysqli 
RUN docker-php-ext-install zip 
RUN docker-php-source delete

#COPY .docker/vhost.conf /etc/apache2/sites-available/000-default.conf

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN a2enmod rewrite

# RUN apt update && apt install -y \
#           libsodium

RUN docker-php-ext-install exif
# RUN docker-php-ext-install sodium

