
# https://devops.tutorials24x7.com/blog/containerize-laravel-with-nginx-mysql-and-mongodb-using-docker-containers

FROM php:8.1-fpm

RUN apt-get update
RUN apt-get install -y openssl zip unzip git curl
RUN apt-get install -y libzip-dev libonig-dev libicu-dev
RUN apt-get install -y autoconf pkg-config libssl-dev mc nodejs npm

RUN docker-php-ext-install bcmath mbstring intl opcache

RUN docker-php-ext-install pdo pdo_mysql mysqli


# from dockerfile-04
#
# RUN apt update && apt install -y \
#         libpng-dev \
#         zlib1g-dev \
#         libxml2-dev \
#         libzip-dev \
# RUN mkdir -p /var/www/html; chown -R 1000:www-data /var/www/html  &&  chmod -R 777 /var/www/html
# WORKDIR /var/www/html
# RUN pwd; ls -la; docker-php-ext-install -j$(nproc) gd 
# RUN docker-php-ext-configure gd 
# RUN docker-php-ext-install pdo_mysql 
# RUN docker-php-ext-install mysqli 
# RUN docker-php-ext-install zip 
# RUN docker-php-source delete
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# RUN a2enmod rewrite
# RUN docker-php-ext-install exif

