# Generated by Django 5.1.1 on 2024-09-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsurveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='structure',
            field=models.JSONField(help_text='Define the structure of the survey as JSON.'),
        ),
    ]
