# Generated by Django 4.1.7 on 2023-07-24 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortorder', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=2930)),
                ('name', models.CharField(max_length=930)),
                ('grouping', models.CharField(max_length=530)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu94app.menuitem')),
            ],
        ),
    ]
