# Generated by Django 4.1.7 on 2023-04-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCpunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchtime', models.DateTimeField()),
                ('duration', models.BigIntegerField()),
                ('machinecell', models.CharField(max_length=303)),
                ('punchtype', models.CharField(max_length=30)),
                ('employee', models.CharField(max_length=303)),
                ('durationtype', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
