# Generated by Django 4.1.7 on 2023-07-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=304)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=305)),
                ('city', models.CharField(max_length=305)),
            ],
        ),
    ]
